// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/sluicev1/sluice.proto

package sluicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mode int32

const (
	// ENFORCE: default. Strip threats and return sanitized bytes.
	Mode_ENFORCE Mode = 0
	// REPORT_ONLY: detect only. Return original bytes unchanged + threat list.
	// Server MUST NOT alter bytes, regardless of what the profile would do.
	Mode_REPORT_ONLY Mode = 1
	// BYPASS_WITH_REPORT: same byte semantics as REPORT_ONLY. Culvert signals
	// VIP/monitor intent via this value; Sluice treats it identically.
	Mode_BYPASS_WITH_REPORT Mode = 2
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "ENFORCE",
		1: "REPORT_ONLY",
		2: "BYPASS_WITH_REPORT",
	}
	Mode_value = map[string]int32{
		"ENFORCE":            0,
		"REPORT_ONLY":        1,
		"BYPASS_WITH_REPORT": 2,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sluicev1_sluice_proto_enumTypes[0].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_proto_sluicev1_sluice_proto_enumTypes[0]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_proto_sluicev1_sluice_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_CLEAN       Status = 0
	Status_SANITIZED   Status = 1
	Status_BLOCKED     Status = 2
	Status_ERROR       Status = 3
	Status_UNSUPPORTED Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "CLEAN",
		1: "SANITIZED",
		2: "BLOCKED",
		3: "ERROR",
		4: "UNSUPPORTED",
	}
	Status_value = map[string]int32{
		"CLEAN":       0,
		"SANITIZED":   1,
		"BLOCKED":     2,
		"ERROR":       3,
		"UNSUPPORTED": 4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sluicev1_sluice_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_sluicev1_sluice_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_sluicev1_sluice_proto_rawDescGZIP(), []int{1}
}

type SanitizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SanitizeRequest_Header
	//	*SanitizeRequest_Chunk
	Payload       isSanitizeRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SanitizeRequest) Reset() {
	*x = SanitizeRequest{}
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizeRequest) ProtoMessage() {}

func (x *SanitizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizeRequest.ProtoReflect.Descriptor instead.
func (*SanitizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_sluicev1_sluice_proto_rawDescGZIP(), []int{0}
}

func (x *SanitizeRequest) GetPayload() isSanitizeRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SanitizeRequest) GetHeader() *SanitizeHeader {
	if x != nil {
		if x, ok := x.Payload.(*SanitizeRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *SanitizeRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*SanitizeRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isSanitizeRequest_Payload interface {
	isSanitizeRequest_Payload()
}

type SanitizeRequest_Header struct {
	Header *SanitizeHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type SanitizeRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*SanitizeRequest_Header) isSanitizeRequest_Payload() {}

func (*SanitizeRequest_Chunk) isSanitizeRequest_Payload() {}

type SanitizeHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ContentLength int64                  `protobuf:"varint,3,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceParent   string                 `protobuf:"bytes,5,opt,name=trace_parent,json=traceParent,proto3" json:"trace_parent,omitempty"` // W3C Traceparent: 00-<trace-id>-<parent-id>-<flags>
	// profile_name: name of the sanitization profile to apply.
	// Empty string is equivalent to "default".
	// Unknown names MUST be rejected with Status=ERROR and
	// error_message="unknown_profile: <name>".
	ProfileName string `protobuf:"bytes,6,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	// mode: how Sluice should treat threats. Server-enforced.
	Mode Mode `protobuf:"varint,7,opt,name=mode,proto3,enum=sluice.v1.Mode" json:"mode,omitempty"`
	// tags: opaque key/value labels. Echoed in logs/metrics only; never
	// branched on. Low-cardinality keys (direction, dest_category) may
	// become Prometheus labels; high-cardinality values go to logs only.
	Tags map[string]string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// policy_version: opaque hash of Culvert's active policy snapshot.
	// Logged for audit correlation. MUST NOT be used as a metric label
	// (cardinality explosion).
	PolicyVersion string `protobuf:"bytes,9,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SanitizeHeader) Reset() {
	*x = SanitizeHeader{}
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizeHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizeHeader) ProtoMessage() {}

func (x *SanitizeHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizeHeader.ProtoReflect.Descriptor instead.
func (*SanitizeHeader) Descriptor() ([]byte, []int) {
	return file_proto_sluicev1_sluice_proto_rawDescGZIP(), []int{1}
}

func (x *SanitizeHeader) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SanitizeHeader) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *SanitizeHeader) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *SanitizeHeader) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SanitizeHeader) GetTraceParent() string {
	if x != nil {
		return x.TraceParent
	}
	return ""
}

func (x *SanitizeHeader) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *SanitizeHeader) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_ENFORCE
}

func (x *SanitizeHeader) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SanitizeHeader) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

type SanitizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SanitizeResponse_Result
	//	*SanitizeResponse_Chunk
	Payload       isSanitizeResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SanitizeResponse) Reset() {
	*x = SanitizeResponse{}
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizeResponse) ProtoMessage() {}

func (x *SanitizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizeResponse.ProtoReflect.Descriptor instead.
func (*SanitizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_sluicev1_sluice_proto_rawDescGZIP(), []int{2}
}

func (x *SanitizeResponse) GetPayload() isSanitizeResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SanitizeResponse) GetResult() *SanitizeResult {
	if x != nil {
		if x, ok := x.Payload.(*SanitizeResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *SanitizeResponse) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*SanitizeResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isSanitizeResponse_Payload interface {
	isSanitizeResponse_Payload()
}

type SanitizeResponse_Result struct {
	Result *SanitizeResult `protobuf:"bytes,1,opt,name=result,proto3,oneof"`
}

type SanitizeResponse_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*SanitizeResponse_Result) isSanitizeResponse_Payload() {}

func (*SanitizeResponse_Chunk) isSanitizeResponse_Payload() {}

type SanitizeResult struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Status       Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=sluice.v1.Status" json:"status,omitempty"`
	OriginalType string                 `protobuf:"bytes,2,opt,name=original_type,json=originalType,proto3" json:"original_type,omitempty"`
	OriginalSize int64                  `protobuf:"varint,3,opt,name=original_size,json=originalSize,proto3" json:"original_size,omitempty"`
	// sanitized_size: size of bytes returned to the client.
	// In REPORT_ONLY / BYPASS_WITH_REPORT modes this equals original_size
	// because the server returns the original bytes unchanged. The
	// "what-would-have-been-sanitized" size is implicit from threats_removed.
	SanitizedSize  int64     `protobuf:"varint,4,opt,name=sanitized_size,json=sanitizedSize,proto3" json:"sanitized_size,omitempty"`
	ThreatsRemoved []*Threat `protobuf:"bytes,5,rep,name=threats_removed,json=threatsRemoved,proto3" json:"threats_removed,omitempty"`
	ErrorMessage   string    `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// sanitized_sha256: SHA-256 of the bytes returned. Lets the client's
	// hash cache skip re-sanitizing identical outputs.
	SanitizedSha256 []byte `protobuf:"bytes,7,opt,name=sanitized_sha256,json=sanitizedSha256,proto3" json:"sanitized_sha256,omitempty"`
	// duration_ms: server-side wall-clock sanitization time.
	DurationMs    int64 `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SanitizeResult) Reset() {
	*x = SanitizeResult{}
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizeResult) ProtoMessage() {}

func (x *SanitizeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizeResult.ProtoReflect.Descriptor instead.
func (*SanitizeResult) Descriptor() ([]byte, []int) {
	return file_proto_sluicev1_sluice_proto_rawDescGZIP(), []int{3}
}

func (x *SanitizeResult) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_CLEAN
}

func (x *SanitizeResult) GetOriginalType() string {
	if x != nil {
		return x.OriginalType
	}
	return ""
}

func (x *SanitizeResult) GetOriginalSize() int64 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

func (x *SanitizeResult) GetSanitizedSize() int64 {
	if x != nil {
		return x.SanitizedSize
	}
	return 0
}

func (x *SanitizeResult) GetThreatsRemoved() []*Threat {
	if x != nil {
		return x.ThreatsRemoved
	}
	return nil
}

func (x *SanitizeResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SanitizeResult) GetSanitizedSha256() []byte {
	if x != nil {
		return x.SanitizedSha256
	}
	return nil
}

func (x *SanitizeResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type Threat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type: opaque, lowercase snake_case (macro, ole_object, javascript,
	// external_ref, launch_action, embedded_file, xfa_form, ...).
	Type        string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Location    string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// severity: MUST be exactly one of {low, medium, high, critical}.
	Severity      string `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Threat) Reset() {
	*x = Threat{}
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Threat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Threat) ProtoMessage() {}

func (x *Threat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Threat.ProtoReflect.Descriptor instead.
func (*Threat) Descriptor() ([]byte, []int) {
	return file_proto_sluicev1_sluice_proto_rawDescGZIP(), []int{4}
}

func (x *Threat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Threat) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Threat) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Threat) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_sluicev1_sluice_proto_rawDescGZIP(), []int{5}
}

type HealthResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	SupportedTypes []string               `protobuf:"bytes,3,rep,name=supported_types,json=supportedTypes,proto3" json:"supported_types,omitempty"`
	ActiveWorkers  int32                  `protobuf:"varint,4,opt,name=active_workers,json=activeWorkers,proto3" json:"active_workers,omitempty"`
	MaxWorkers     int32                  `protobuf:"varint,5,opt,name=max_workers,json=maxWorkers,proto3" json:"max_workers,omitempty"`
	QueueDepth     int32                  `protobuf:"varint,6,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	FilesProcessed int64                  `protobuf:"varint,7,opt,name=files_processed,json=filesProcessed,proto3" json:"files_processed,omitempty"`
	ThreatsRemoved int64                  `protobuf:"varint,8,opt,name=threats_removed,json=threatsRemoved,proto3" json:"threats_removed,omitempty"`
	// profiles: sanitization profiles this server offers. Used by Culvert's
	// admin GUI to present a profile picker. v0.1 ships with a single
	// "default" profile; v0.2+ adds aggressive, relaxed, etc.
	Profiles      []*Profile `protobuf:"bytes,9,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_sluicev1_sluice_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetSupportedTypes() []string {
	if x != nil {
		return x.SupportedTypes
	}
	return nil
}

func (x *HealthResponse) GetActiveWorkers() int32 {
	if x != nil {
		return x.ActiveWorkers
	}
	return 0
}

func (x *HealthResponse) GetMaxWorkers() int32 {
	if x != nil {
		return x.MaxWorkers
	}
	return 0
}

func (x *HealthResponse) GetQueueDepth() int32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *HealthResponse) GetFilesProcessed() int64 {
	if x != nil {
		return x.FilesProcessed
	}
	return 0
}

func (x *HealthResponse) GetThreatsRemoved() int64 {
	if x != nil {
		return x.ThreatsRemoved
	}
	return 0
}

func (x *HealthResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type Profile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name: lowercase-hyphenated, stable once published. "default" is reserved.
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// capabilities: opaque strings describing what this profile does
	// (e.g. strip_macros, strip_js, strip_ole, re_encode_images, strip_xfa).
	Capabilities []string `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// max_file_size_bytes: 0 = use server default.
	MaxFileSizeBytes int64 `protobuf:"varint,4,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_proto_sluicev1_sluice_proto_rawDescGZIP(), []int{7}
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Profile) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Profile) GetMaxFileSizeBytes() int64 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_proto_sluicev1_sluice_proto_rawDescGZIP(), []int{8}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaCert        []byte                 `protobuf:"bytes,1,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	ClientCert    []byte                 `protobuf:"bytes,2,opt,name=client_cert,json=clientCert,proto3" json:"client_cert,omitempty"`
	ClientKey     []byte                 `protobuf:"bytes,3,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	Endpoint      string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluicev1_sluice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_proto_sluicev1_sluice_proto_rawDescGZIP(), []int{9}
}

func (x *EnrollResponse) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *EnrollResponse) GetClientCert() []byte {
	if x != nil {
		return x.ClientCert
	}
	return nil
}

func (x *EnrollResponse) GetClientKey() []byte {
	if x != nil {
		return x.ClientKey
	}
	return nil
}

func (x *EnrollResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

var File_proto_sluicev1_sluice_proto protoreflect.FileDescriptor

const file_proto_sluicev1_sluice_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/sluicev1/sluice.proto\x12\tsluice.v1\"i\n" +
	"\x0fSanitizeRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x19.sluice.v1.SanitizeHeaderH\x00R\x06header\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"\x99\x03\n" +
	"\x0eSanitizeHeader\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12%\n" +
	"\x0econtent_length\x18\x03 \x01(\x03R\rcontentLength\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12!\n" +
	"\ftrace_parent\x18\x05 \x01(\tR\vtraceParent\x12!\n" +
	"\fprofile_name\x18\x06 \x01(\tR\vprofileName\x12#\n" +
	"\x04mode\x18\a \x01(\x0e2\x0f.sluice.v1.ModeR\x04mode\x127\n" +
	"\x04tags\x18\b \x03(\v2#.sluice.v1.SanitizeHeader.TagsEntryR\x04tags\x12%\n" +
	"\x0epolicy_version\x18\t \x01(\tR\rpolicyVersion\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x10SanitizeResponse\x123\n" +
	"\x06result\x18\x01 \x01(\v2\x19.sluice.v1.SanitizeResultH\x00R\x06result\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"\xd9\x02\n" +
	"\x0eSanitizeResult\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.sluice.v1.StatusR\x06status\x12#\n" +
	"\roriginal_type\x18\x02 \x01(\tR\foriginalType\x12#\n" +
	"\roriginal_size\x18\x03 \x01(\x03R\foriginalSize\x12%\n" +
	"\x0esanitized_size\x18\x04 \x01(\x03R\rsanitizedSize\x12:\n" +
	"\x0fthreats_removed\x18\x05 \x03(\v2\x11.sluice.v1.ThreatR\x0ethreatsRemoved\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12)\n" +
	"\x10sanitized_sha256\x18\a \x01(\fR\x0fsanitizedSha256\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x03R\n" +
	"durationMs\"v\n" +
	"\x06Threat\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\"\x0f\n" +
	"\rHealthRequest\"\xd8\x02\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12'\n" +
	"\x0fsupported_types\x18\x03 \x03(\tR\x0esupportedTypes\x12%\n" +
	"\x0eactive_workers\x18\x04 \x01(\x05R\ractiveWorkers\x12\x1f\n" +
	"\vmax_workers\x18\x05 \x01(\x05R\n" +
	"maxWorkers\x12\x1f\n" +
	"\vqueue_depth\x18\x06 \x01(\x05R\n" +
	"queueDepth\x12'\n" +
	"\x0ffiles_processed\x18\a \x01(\x03R\x0efilesProcessed\x12'\n" +
	"\x0fthreats_removed\x18\b \x01(\x03R\x0ethreatsRemoved\x12.\n" +
	"\bprofiles\x18\t \x03(\v2\x12.sluice.v1.ProfileR\bprofiles\"\x92\x01\n" +
	"\aProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12-\n" +
	"\x13max_file_size_bytes\x18\x04 \x01(\x03R\x10maxFileSizeBytes\"%\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x85\x01\n" +
	"\x0eEnrollResponse\x12\x17\n" +
	"\aca_cert\x18\x01 \x01(\fR\x06caCert\x12\x1f\n" +
	"\vclient_cert\x18\x02 \x01(\fR\n" +
	"clientCert\x12\x1d\n" +
	"\n" +
	"client_key\x18\x03 \x01(\fR\tclientKey\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint*<\n" +
	"\x04Mode\x12\v\n" +
	"\aENFORCE\x10\x00\x12\x0f\n" +
	"\vREPORT_ONLY\x10\x01\x12\x16\n" +
	"\x12BYPASS_WITH_REPORT\x10\x02*K\n" +
	"\x06Status\x12\t\n" +
	"\x05CLEAN\x10\x00\x12\r\n" +
	"\tSANITIZED\x10\x01\x12\v\n" +
	"\aBLOCKED\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\x0f\n" +
	"\vUNSUPPORTED\x10\x042\xd6\x01\n" +
	"\rSluiceService\x12G\n" +
	"\bSanitize\x12\x1a.sluice.v1.SanitizeRequest\x1a\x1b.sluice.v1.SanitizeResponse(\x010\x01\x12=\n" +
	"\x06Health\x12\x18.sluice.v1.HealthRequest\x1a\x19.sluice.v1.HealthResponse\x12=\n" +
	"\x06Enroll\x12\x18.sluice.v1.EnrollRequest\x1a\x19.sluice.v1.EnrollResponseB+Z)github.com/KidCarmi/Sluice/proto/sluicev1b\x06proto3"

var (
	file_proto_sluicev1_sluice_proto_rawDescOnce sync.Once
	file_proto_sluicev1_sluice_proto_rawDescData []byte
)

func file_proto_sluicev1_sluice_proto_rawDescGZIP() []byte {
	file_proto_sluicev1_sluice_proto_rawDescOnce.Do(func() {
		file_proto_sluicev1_sluice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sluicev1_sluice_proto_rawDesc), len(file_proto_sluicev1_sluice_proto_rawDesc)))
	})
	return file_proto_sluicev1_sluice_proto_rawDescData
}

var file_proto_sluicev1_sluice_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_sluicev1_sluice_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_sluicev1_sluice_proto_goTypes = []any{
	(Mode)(0),                // 0: sluice.v1.Mode
	(Status)(0),              // 1: sluice.v1.Status
	(*SanitizeRequest)(nil),  // 2: sluice.v1.SanitizeRequest
	(*SanitizeHeader)(nil),   // 3: sluice.v1.SanitizeHeader
	(*SanitizeResponse)(nil), // 4: sluice.v1.SanitizeResponse
	(*SanitizeResult)(nil),   // 5: sluice.v1.SanitizeResult
	(*Threat)(nil),           // 6: sluice.v1.Threat
	(*HealthRequest)(nil),    // 7: sluice.v1.HealthRequest
	(*HealthResponse)(nil),   // 8: sluice.v1.HealthResponse
	(*Profile)(nil),          // 9: sluice.v1.Profile
	(*EnrollRequest)(nil),    // 10: sluice.v1.EnrollRequest
	(*EnrollResponse)(nil),   // 11: sluice.v1.EnrollResponse
	nil,                      // 12: sluice.v1.SanitizeHeader.TagsEntry
}
var file_proto_sluicev1_sluice_proto_depIdxs = []int32{
	3,  // 0: sluice.v1.SanitizeRequest.header:type_name -> sluice.v1.SanitizeHeader
	0,  // 1: sluice.v1.SanitizeHeader.mode:type_name -> sluice.v1.Mode
	12, // 2: sluice.v1.SanitizeHeader.tags:type_name -> sluice.v1.SanitizeHeader.TagsEntry
	5,  // 3: sluice.v1.SanitizeResponse.result:type_name -> sluice.v1.SanitizeResult
	1,  // 4: sluice.v1.SanitizeResult.status:type_name -> sluice.v1.Status
	6,  // 5: sluice.v1.SanitizeResult.threats_removed:type_name -> sluice.v1.Threat
	9,  // 6: sluice.v1.HealthResponse.profiles:type_name -> sluice.v1.Profile
	2,  // 7: sluice.v1.SluiceService.Sanitize:input_type -> sluice.v1.SanitizeRequest
	7,  // 8: sluice.v1.SluiceService.Health:input_type -> sluice.v1.HealthRequest
	10, // 9: sluice.v1.SluiceService.Enroll:input_type -> sluice.v1.EnrollRequest
	4,  // 10: sluice.v1.SluiceService.Sanitize:output_type -> sluice.v1.SanitizeResponse
	8,  // 11: sluice.v1.SluiceService.Health:output_type -> sluice.v1.HealthResponse
	11, // 12: sluice.v1.SluiceService.Enroll:output_type -> sluice.v1.EnrollResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_sluicev1_sluice_proto_init() }
func file_proto_sluicev1_sluice_proto_init() {
	if File_proto_sluicev1_sluice_proto != nil {
		return
	}
	file_proto_sluicev1_sluice_proto_msgTypes[0].OneofWrappers = []any{
		(*SanitizeRequest_Header)(nil),
		(*SanitizeRequest_Chunk)(nil),
	}
	file_proto_sluicev1_sluice_proto_msgTypes[2].OneofWrappers = []any{
		(*SanitizeResponse_Result)(nil),
		(*SanitizeResponse_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sluicev1_sluice_proto_rawDesc), len(file_proto_sluicev1_sluice_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sluicev1_sluice_proto_goTypes,
		DependencyIndexes: file_proto_sluicev1_sluice_proto_depIdxs,
		EnumInfos:         file_proto_sluicev1_sluice_proto_enumTypes,
		MessageInfos:      file_proto_sluicev1_sluice_proto_msgTypes,
	}.Build()
	File_proto_sluicev1_sluice_proto = out.File
	file_proto_sluicev1_sluice_proto_goTypes = nil
	file_proto_sluicev1_sluice_proto_depIdxs = nil
}
