// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/sluicev1/sluice.proto

package sluicev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SluiceService_Sanitize_FullMethodName = "/sluice.v1.SluiceService/Sanitize"
	SluiceService_Health_FullMethodName   = "/sluice.v1.SluiceService/Health"
	SluiceService_Enroll_FullMethodName   = "/sluice.v1.SluiceService/Enroll"
)

// SluiceServiceClient is the client API for SluiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SluiceServiceClient interface {
	// Sanitize processes a file and returns the sanitized version.
	// Streaming: client sends SanitizeHeader first, then bytes chunks.
	// Server responds with SanitizeResult first (always atomically),
	// then zero or more bytes chunks of sanitized content.
	// Do NOT interleave Threat objects after chunks start.
	Sanitize(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SanitizeRequest, SanitizeResponse], error)
	// Health returns the service status, capabilities, and available profiles.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Enroll exchanges a one-time enrollment token for mTLS client certificates.
	// Does NOT require a client cert (chicken-and-egg). Clients must TOFU-verify
	// the server cert fingerprint before sending the token.
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
}

type sluiceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSluiceServiceClient(cc grpc.ClientConnInterface) SluiceServiceClient {
	return &sluiceServiceClient{cc}
}

func (c *sluiceServiceClient) Sanitize(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SanitizeRequest, SanitizeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SluiceService_ServiceDesc.Streams[0], SluiceService_Sanitize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SanitizeRequest, SanitizeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SluiceService_SanitizeClient = grpc.BidiStreamingClient[SanitizeRequest, SanitizeResponse]

func (c *sluiceServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SluiceService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sluiceServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, SluiceService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SluiceServiceServer is the server API for SluiceService service.
// All implementations must embed UnimplementedSluiceServiceServer
// for forward compatibility.
type SluiceServiceServer interface {
	// Sanitize processes a file and returns the sanitized version.
	// Streaming: client sends SanitizeHeader first, then bytes chunks.
	// Server responds with SanitizeResult first (always atomically),
	// then zero or more bytes chunks of sanitized content.
	// Do NOT interleave Threat objects after chunks start.
	Sanitize(grpc.BidiStreamingServer[SanitizeRequest, SanitizeResponse]) error
	// Health returns the service status, capabilities, and available profiles.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Enroll exchanges a one-time enrollment token for mTLS client certificates.
	// Does NOT require a client cert (chicken-and-egg). Clients must TOFU-verify
	// the server cert fingerprint before sending the token.
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	mustEmbedUnimplementedSluiceServiceServer()
}

// UnimplementedSluiceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSluiceServiceServer struct{}

func (UnimplementedSluiceServiceServer) Sanitize(grpc.BidiStreamingServer[SanitizeRequest, SanitizeResponse]) error {
	return status.Error(codes.Unimplemented, "method Sanitize not implemented")
}
func (UnimplementedSluiceServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSluiceServiceServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedSluiceServiceServer) mustEmbedUnimplementedSluiceServiceServer() {}
func (UnimplementedSluiceServiceServer) testEmbeddedByValue()                       {}

// UnsafeSluiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SluiceServiceServer will
// result in compilation errors.
type UnsafeSluiceServiceServer interface {
	mustEmbedUnimplementedSluiceServiceServer()
}

func RegisterSluiceServiceServer(s grpc.ServiceRegistrar, srv SluiceServiceServer) {
	// If the following call panics, it indicates UnimplementedSluiceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SluiceService_ServiceDesc, srv)
}

func _SluiceService_Sanitize_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SluiceServiceServer).Sanitize(&grpc.GenericServerStream[SanitizeRequest, SanitizeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SluiceService_SanitizeServer = grpc.BidiStreamingServer[SanitizeRequest, SanitizeResponse]

func _SluiceService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SluiceServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SluiceService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SluiceServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SluiceService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SluiceServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SluiceService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SluiceServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SluiceService_ServiceDesc is the grpc.ServiceDesc for SluiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SluiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sluice.v1.SluiceService",
	HandlerType: (*SluiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _SluiceService_Health_Handler,
		},
		{
			MethodName: "Enroll",
			Handler:    _SluiceService_Enroll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sanitize",
			Handler:       _SluiceService_Sanitize_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/sluicev1/sluice.proto",
}
